version: '3.8'
services:

  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9000:9200"
    networks:
      - tools
  
  fluentd:
    build: ./fluentd
    container_name: fluentd
    links:
      - "elasticsearch"
    ports:
      - "9001:24224"
      - "9001:24224/udp"
    networks:
      - tools

  kibana:
    build: ./kibana
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "9002:5601"
    networks:
      - tools

  prometheus:
    build: ./prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    restart: unless-stopped
    ports:
      - "9003:9090"
    networks:
      - tools    

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "9004:3000"

networks:
  tools:
    external:
      name: tools

volumes:
  prometheus_data: {}
  grafana_data: {}


